# Server Configuration
server:
  port: 8080

# Application Configuration
spring:
  application:
    name: hello-quick
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:30306/helloquick?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: helloquick
    password: helloquick123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update  # 改为update模式，允许自动更新表结构
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        '[format_sql]': true
        '[use_sql_comments]': true

  # Profile Configuration
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Redis Configuration
  data:
    redis:
      host: redis.default.svc.cluster.local
      port: 6379
      password: 
      database: 0
      timeout: 2000ms
      connect-timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

  # Cache Configuration
  cache:
    type: redis
    cache-names: 
      - "user"
      - "userStats" 
      - "session"
      - "rateLimit"
    redis:
      time-to-live: 600000  # 10 minutes default TTL
      enable-statistics: true
      use-key-prefix: true
      key-prefix: "hello-quick:cache:"



---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  
  # 开发环境Redis配置
  data:
    redis:
      host: localhost
      port: 30379
      password: 
      database: 0
      timeout: 2000ms
      connect-timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

  # 开发环境缓存配置
  cache:
    redis:
      time-to-live: 300000  # 5 minutes for dev
      enable-statistics: true

# 开发环境安全配置
app:
  security:
    jwt:
      secret: hello-quick-dev-secret
      expiration: 86400
    allowed-ips:
      - "127.0.0.1"
      - "::1"
      - "192.168.0.0/16"

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod

# 生产环境安全配置
app:
  security:
    jwt:
      secret: ${JWT_SECRET:hello-quick-prod-secret}
      expiration: 3600
    allowed-ips: 
      - "127.0.0.1"
      - "192.168.0.0/16"
      - "10.0.0.0/8"

# Management Configuration (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches,redis
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    caches:
      access: READ_ONLY
  # 暂时禁用可能导致循环依赖的metrics配置
  # simple:
  #   metrics:
  #     export:
  #       enabled: true
  # metrics:
  #   distribution:
  #     percentiles-histogram:
  #       redis: true
  #       cache: true

# Logging Configuration
logging:
  level:
    com:
      kinkle: INFO
    org:
      springframework:
        web: DEBUG
        cache: DEBUG
        data:
          redis: DEBUG


