# 测试环境配置
spring:
  application:
    name: hello-quick-test
  
  # 测试数据库配置 - 使用H2内存数据库
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # JPA测试配置
  jpa:
    hibernate:
      ddl-auto: create-drop  # 测试时自动创建和删除表
    show-sql: false         # 测试时不显示SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        '[format_sql]': false
        '[use_sql_comments]': false
  
  # H2控制台配置（测试调试用）
  h2:
    console:
      enabled: true
      path: /h2-console

# 测试环境安全配置
app:
  security:
    jwt:
      secret: test-secret-key
      expiration: 3600
    allowed-ips:
      - "127.0.0.1"


