# Server Configuration
server:
  port: 8080

# Application Configuration
spring:
  application:
    name: hello-quick
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://mysql.mysql.svc.cluster.local:3306/helloquick?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: helloquick
    password: helloquick123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        '[format_sql]': true
        '[use_sql_comments]': true

  # Profile Configuration
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}



---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev

# 开发环境安全配置
app:
  security:
    jwt:
      secret: hello-quick-dev-secret
      expiration: 86400
    allowed-ips:
      - "127.0.0.1"
      - "::1"
      - "192.168.0.0/16"

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod

# 生产环境安全配置
app:
  security:
    jwt:
      secret: ${JWT_SECRET:hello-quick-prod-secret}
      expiration: 3600
    allowed-ips: 
      - "127.0.0.1"
      - "192.168.0.0/16"
      - "10.0.0.0/8"

# Logging Configuration
logging:
  level:
    com:
      kinkle: INFO
    org:
      springframework:
        web: DEBUG


